# Generated by Django 3.2.9 on 2021-11-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='achats',
        ),
        migrations.AddField(
            model_name='client',
            name='achats',
            field=models.ManyToManyField(blank=True, related_name='achats', to='clients.Achat'),
        ),
    ]
